sfcrmmulesoftstarterapp/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UniversityCRM/force-app/main/default/objects/Course__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfcrmmulesoftstarterapp/force-app/main/default/classes/CourseService.cls
public with sharing class CourseService {

    public static void validateCourse(Course__c c) {

        if (String.isBlank(c.Name)) {
            throw new IllegalArgumentException('Course Name is required');
        }

        if (String.isBlank(c.Code__c)) {
            throw new IllegalArgumentException('Course Code is required');
        }
    }

    public static List<Course__c> getCourses() {

        return [
            SELECT Id, Name, Code__c
            FROM Course__c
        ];
    }

    public static void createCourse(Course__c c) {

        validateCourse(c);

        try {

            insert c;

        } catch (DmlException ex) {

            throw new AuraHandledException(
                'Unable to create course'
            );
        }
    }
}