UniversityCRM/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>STU-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UniversityCRM/force-app/main/default/objects/Student__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <label>GPA</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

UniversityCRM/force-app/main/default/objects/Student__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfcrmmulesoftstarterapp/force-app/main/default/objects/Student__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>First Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfcrmmulesoftstarterapp/force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UniversityCRM/force-app/main/default/classes/StudentService.cls
public with sharing class StudentService {

    public class StudentException extends Exception{
    }
    private static final Decimal GPA_MIN = 0;
    private static final Decimal GPS_MAX = 4;


    public static void validateStudent(List<Student__c> students) {

        if(students == null || students.isEmpty()) return;

        for (Student__c S:students){
            if (String.isBlank(S.Email__c)) {
                throw new StudentException('Email is required');
            }

            if (S.GPA__c != null && (S.GPA__c < GPA_MIN ||S.GPA__c > GPS_MAX)) {
                throw new StudentException('GPA must be between 0 and 4');
            }

            if(String.isBlank(S.Name__c) || String.isBlank(S.Last_Name__c)){
                throw new StudentException('First Name and Last Name required');
            }
        }
    }
    

    @AuraEnabled(cacheable=true)
    public static List<Student__c> getStudents(Integer recordLimit) {
        Integer safeLimit = (recordLimit == null || recordLimit <= 0)
        ? 50 : Math.min(recordLimit,2000);
        return [
            SELECT Id, Name__c,Last_Name__c, Email__c, GPA__c, Status__c
            FROM Student__c with USER_MODE
            ORDER BY CreatedDate DESC
            LIMIT :safeLimit];
    }

  
    public static Id createStudent(Student__c s){
        try {
            validateStudent(new List<Student__c> { s });
            insert as user s;
            return s.Id;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}