UniversityCRM/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>STU-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UniversityCRM/force-app/main/default/objects/Student__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <label>GPA</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

sfcrmmulesoftstarterapp/force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfcrmmulesoftstarterapp/force-app/main/default/classes/StudentService.cls
public with sharing class StudentService {

    public static void validateStudent(Student__c s) {

        if (String.isBlank(s.Email__c)) {
            throw new IllegalArgumentException('Email is required');
        }

        if (s.GPA__c < 0 || s.GPA__c > 5) {
            throw new IllegalArgumentException('GPA must be between 0 and 10');
        }
    }

    public static List<Student__c> getStudents() {

        return [
            SELECT Id, Name, Email__c, GPA__c, Status__c
            FROM Student__c
        ];
    }
}