UniversityCRM/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>STU-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UniversityCRM/force-app/main/default/objects/Student__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <label>GPA</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

sfcrmmulesoftstarterapp/force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UniversityCRM/force-app/main/default/classes/StudentTriggerHandler.cls
public with sharing class StudentTriggerHandler extends TriggerHandler{
    private List<Student__c> newList = (List<Student__c>) Trigger.new;
    protected override void beforeInsert() { applyStatusFromGpa(newList);}
    protected override void beforeUpdate() { applyStatusFromGpa(newList);}  
    private static final Decimal GPS_MIN = 2.3;

    @TestVisible
    private static void applyStatusFromGpa(List<Student__c> students){
        if (students == null) return;
        for(Student__c s:students){
            if(s.GPA__c != null && s.GPA__c > GPS_MIN){
                s.Status__c = 'Active';
            }else{
                s.Status__c = 'New';
            }
        }
    }
}