UniversityCRM/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>STU-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UniversityCRM/force-app/main/default/objects/Student__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <label>GPA</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

sfcrmmulesoftstarterapp/force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfcrmmulesoftstarterapp/force-app/main/default/classes/StudentServiceText.cls
@isTest
private class StudentServiceTest {

    @isTest
    static void testGetStudents() {

        Student__c s = new Student__c(
            Name = 'John Doe',
            Email__c = 'john@test.com',
            GPA__c = 8,
            Status__c = 'Active'
        );

        insert s;

        Test.startTest();

        List<Student__c> result = StudentService.getStudents();

        Test.stopTest();

        System.assert(result.size() > 0);
    }

    @isTest
    static void testValidation() {

        Student__c s = new Student__c(
            Name = 'Bad Student',
            GPA__c = 20
        );

        try {

            StudentService.validateStudent(s);

            System.assert(false);

        } catch (Exception e) {

            System.assertEquals(
                'Email is required',
                e.getMessage()
            );
        }
    }
}