UniversityCRM/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UniversityCRM/force-app/main/default/objects/Course__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

UniversityCRM/force-app/main/default/objects/Course__c/fields/Course_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Course_End_Date__c</fullName>
    <label>Course End Date</label>
    <type>Date</type>
</CustomField>

UniversityCRM/force-app/main/default/objects/Course__c/fields/Course_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Course_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Course External Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

UniversityCRM/force-app/main/default/objects/Course__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>70</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

UniversityCRM/force-app/main/default/objects/Course__c/fields/Credits__c.field-meta.xml
<CustomField>
    <fullName>Credits__c</fullName>
    <label>Credits</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

UniversityCRM/force-app/main/default/objects/Course__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Computer Science</fullName>
            </value>
            <value>
                <fullName>Mathematics</fullName>
            </value>
            <value>
                <fullName>Biology</fullName>
            </value>
            <value>
                <fullName>Psychology</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UniversityCRM/force-app/main/default/objects/Course__c/fields/Max_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Max_Capacity__c</fullName>
    <label>Max Capacity</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfcrmmulesoftstarterapp/force-app/main/default/objects/Course__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>70</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

UniversityCRM/force-app/main/default/objects/Course__c/fields/Semester__c.field-meta.xml
<CustomField>
    <fullName>Semester__c</fullName>
    <label>Semester</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fall</fullName>
            </value>
            <value>
                <fullName>Spring</fullName>
            </value>
            <value>
                <fullName>Summer</fullName>
            </value>
            <value>
                <fullName>Winter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UniversityCRM/force-app/main/default/objects/Course__c/fields/Total_students_enrolled__c.field-meta.xml
<CustomField>
    <fullName>Total_students_enrolled__c</fullName>
    <label>Total students enrolled</label>
    <summaryForeignKey>Enrollment__c.Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

UniversityCRM/force-app/main/default/classes/CourseController.cls
public with sharing class CourseController {
    @AuraEnabled(cacheable=true)
    public static List<Course__c> getCourses() {
        return [
            SELECT Id, Code__c, Course_End_Date__c, Course_External_Id__c, Course_Name__c,
            Credits__c, Department__c, Name, Is_Active__c,Semester__C,
            Max_Capacity__c, Name__c, Total_students_enrolled__c
            FROM Course__c
            ORDER BY Name
            LIMIT 50
        ];
    }
}